version: "3.9"

services:
  postgres:
    container_name: linkshortenerdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=linkshortener
    command: -p 5433
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./src/db/seed.sql:/docker-entrypoint-initdb.d/create_tables.sql
  express:
    restart: always
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - PORT=8000
      - PGUSER=me
      - PGHOST=linkshortenerdb
      - PGPASSWORD=password
      - PGDATABASE=linkshortener
      - PGPORT=5433
      - SHORTLENGTH=8
    ports:
      - "8000:8000"
